from .fast_parallel_velocity_model_gradient_calculator import FastParallelVelocityModelGradientCalculator, FastParallelVelocityModelProps
from .velocity_model_gradient_calculator import VelocityModelGradientCalculator
