from .fast_parallel_velocity_model_gradient_calculator import FastParallelVelocityModelGradientCalculator, FastParallelVelocityModelGradientCalculatorProps
from .velocity_model_gradient_calculator import VelocityModelGradientCalculator
