name: Revet Deploy

on:
  delete

jobs:
  revert-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs
        uses: actions/checkout@v4
        with:
          ref: docs
      - name: Commit docs
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git rm -rf --ignore-unmatch ${{ github.event.ref }}
          git commit --no-verify -m "Pushed by GitHub Actions"
          git push -f origin docs
